& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "Save_the_Monk2" `
  -ModName "Save the Monk 2" `
  -ModFolder "savethemonk2" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/save-the-monk2/Save-the-Monk-2-Original.zip" `
  -ModBaseFilesUrlHash "c055eea0cf386fd037623de40242ef242c2125adf4eff8e0213e75ed679b130f" `
  -ModReadmePath "readme.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
